package org.webbuilder.persistence;

import org.webbuilder.persistence.base.BaseDatasource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Datasource extends BaseDatasource<Datasource> {
	public static final Datasource dao = new Datasource();
}
