package org.webbuilder.persistence;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class MappingKit {
	//default primary key
	private static final String guid = "guid";
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("webdb_datasource", guid, Datasource.class);
		arp.addMapping("webdb_menus", guid, Menus.class);
		arp.addMapping("webdb_user", guid, User.class);
	}
}

