package org.webbuilder.persistence;

import org.webbuilder.persistence.base.BaseMenus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menus extends BaseMenus<Menus> {
	public static final Menus dao = new Menus();
}
